# Introduction

Working with numbers is central to almost all scientific and engineering computations. 
The topic is so important that there are many dedicated libraries to help implement efficient numerical
computations. There are even languages that are specifically designed for numerical computation, such as Fortran
and MATLAB.

NumPy (http://www.numpy.org/) is the most widely used Python library for numerical computations.  It provides an extensive range of data structures and functions for numerical
computation. In this notebook we will explore just some of the functionality.
You will be seeing NumPy in other courses. NumPy can perform many of the operations that you will learn
during the mathematics courses.

Another library, which largely builds on NumPy and provides additional functionality, is SciPy (https://www.scipy.org/). SciPy provides some  more specialised data structures and functions over NumPy. 
If you are familiar with MATLAB, NumPy and SciPy provide much of what is available in MATLAB.

NumPy is a large and extensive library and this activity is just a very brief introduction.
To discover how to perform operations with NumPy, your best resources are search engines, such as http://stackoverflow.com/.


## Objectives

- Introduction to 1D and 2D arrays (vector and matrices) 
- Manipulating arrays (indexing, slicing, etc)
- Apply elementary numerical operations
- Demonstrate efficiency differences between vectorised and non-vectorised functions

# Importing the NumPy module

To make NumPy available in our programs, we need to import the module. It has become an informal custom to import NumPy using the shortcut '`np`': 

In [46]:
import numpy as np
import math as math

# Numerical arrays

We have already seen Python 'lists', which hold 'arrays' of data.  We can access the elements of a list using an index because the entries are stored in order. Python lists are very flexible and can hold mixed data types, e.g. combinations of floats and strings, or even lists of lists of lists . . .

The flexibility of Python lists comes at the expense of performance. Many science, engineering and mathematics problems involve very large problems with operations on numbers, and computational speed is important for large problems. To serve this need, we normally use specialised functions and data structures for numerical computation, and in particular for arrays of numbers. Some of the flexibility of lists is traded for performance.

## One-dimensional arrays

A one-dimensional array is a collection of numbers which we can access by index (it preserves order).

### Creating arrays and indexing 

To create a NumPy array of length 10 and initially filled with zeros:

In [47]:
x = np.zeros(10)

print(x)
print(type(x))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


The default type of a NumPy array is `float`. The type can be checked with

In [49]:
print(x.dtype)

float64


You cannot, for example, add a `string` to a `numpy.ndarray`. All entries in the array have the same type.

We can check the length of an array using `len`, which gives the number of entries in the array:

In [50]:
print(len(x))

10


A better way to check the length is to use `x.shape`, which returns a tuple with the dimensions of the array:

In [51]:
print(x.shape)

(10,)


`shape` tells us the size of the array in *each* direction. We will see two-dimensional arrays shortly (matrices), which have a size in each direction.

We can change the entries of an array using indexing,

In [52]:
print(x)

x[0] = 10.0
x[3] = -4.3
x[9] = 1.0

print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[10.   0.   0.  -4.3  0.   0.   0.   0.   0.   1. ]


Remember that indexing starts from zero!

There are other ways to create arrays, such as an array of 'ones':

In [53]:
y = np.ones(5)
print(y)

[1. 1. 1. 1. 1.]


an array of random values:

In [54]:
y = np.random.rand(6)
print(y)

[0.22045826 0.61006113 0.62372332 0.04388343 0.29866852 0.01286883]


or a NumPy array from a Python list:

In [56]:
x = [4.0, 8.0, 9.0, 11.0, -2.0]
y = np.array(x)
print(y)
print(x)

[ 4.  8.  9. 11. -2.]
[4.0, 8.0, 9.0, 11.0, -2.0]


Two more methods for creating arrays which we will use in later notebooks are:

- `numpy.arange`; and 
- `numpy.linspace`. 

They are particularly useful for plotting functions.
The function `arange` creates an array with equally spaced values. It is similar in some cases to `range`, which we have seen earlier. To create the array `[0 1 2 3 4 5]` using `arange`:

In [57]:
x = np.arange(6)
print(x)
print(type(x))

[0 1 2 3 4 5]
<class 'numpy.ndarray'>


Note that '6' is not included. We can change the start value, e.g.:

In [58]:
x = np.arange(2, 6)
print(x)

[2 3 4 5]


The function `linspace` creates an array with prescribed start and end values (both are included), and a prescribed number on values, all equally spaced:

In [64]:
x = np.linspace(0,2*math.pi,100)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

The `linspace` function is used extensively for plotting, as we will see in the next notebook.

### Array arithmetic and functions

NumPy arrays support common arithmetic operations, such as addition of two arrays

In [66]:
x = np.array([1.0, 0.2, 1.2])
y = np.array([2.0, 0.1, 2.1])
print(x)
print(y)

# Sum x and y
z = x + y
print(z)

[1.  0.2 1.2]
[2.  0.1 2.1]
[3.  0.3 3.3]


and multiplication of components by a scalar,

In [67]:
z = 10.0*x
print(z)

[10.  2. 12.]


and raising components to a power:

In [68]:
x = np.array([2, 3, 4])
print(x**2)

[ 4  9 16]


We can also apply functions to the components of an array:

In [73]:
# Create an array [0, π/2, π, 3π/2]
x = np.array([0.0, np.pi/2, np.pi, 3*np.pi/2])
print(x)

# Compute sine of each entry
y = np.sin(x)
print(y)

[0.         1.57079633 3.14159265 4.71238898]
[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


The above has computed the sine of each entry in the array `x`.

Note that the function `np.sin` is used, and not `math.sin` (which was used in previous notebooks). The reason is that `np.sin` is more general -  it can act on lists/arrays of values rather than on just one value. We will apply functions to arrays in the next notebook to plot functions.

We could have computed the sine of each array entry using `for` loops:

In [74]:
y = np.zeros(len(x))
for i in range(len(x)):
    y[i] = np.sin(x[i])

print(y)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


but the program becomes longer and harder to read. Additionally, in many cases it will be much slower. 
You might see manipulation of arrays without indexing referred to as 'vectorisation'. When possible, vectorisation is a good thing to do. We compare the performance of indexing versus vectorisation below.

### Performance example: computing the norm of a long vector

The norm of a vector $x$ is given by: 

$$
\| x \| = \sqrt{\sum_{i=0}^{n-1} x_{i} x_{i}}
$$

where $x_{i}$ is the $i$th entry of $x$. It is the dot product of a vector with itself, 
followed by taking the square root.
To compute the norm, we could loop/iterate over the entries of the vector and sum the square of each entry, and then take the square root of the result.

We will evaluate the norm using two methods for computing the norm of an array of length 10 million to compare their performance. We first create a vector with 10 million random entries, using NumPy:

In [75]:
# Create a NumPy array with 10 million random values
x = np.random.rand(10000000)
print(type(x))

<class 'numpy.ndarray'>


We now time how long it takes to compute the norm of the vector using the NumPy function '`numpy.dot`'. We use the Jupyter 'magic command' [`%time`](Notebook%20tips.ipynb#Simple-timing) to time the operation: 

In [76]:
%time norm = np.sqrt(np.dot(x, x))
print(norm)

CPU times: user 11.4 ms, sys: 18.8 ms, total: 30.2 ms
Wall time: 18.8 ms
1825.9657997479014


The time output of interest is '`Wall time`'.

> The details of how `%time` works are not important for this course. We use it as a compact and covenient tool to 
> measure how much time a command takes to execute.

We now perform the same operation with our own function for computing the norm:

In [77]:
def compute_norm(x):
    norm = 0.0
    for xi in x:
        norm += xi*xi
    return np.sqrt(norm)

%time norm =compute_norm(x)
print(norm)

CPU times: user 1.4 s, sys: 4.81 ms, total: 1.41 s
Wall time: 1.41 s
1825.9657997476795


You should see that the two approaches give the same result, but the 
NumPy function is more than 100 times faster, and possibly more than 100,000 times faster!

The message is that specialised functions and data structures for numerical computations can be many orders of magnitude faster than your own general implementations. On top of that, the specialised functions are much less 
likely to have bugs!

## Two-dimensional arrays

Two-dimensional arrays are very useful for arranging data in many engineering applications and for performing mathematical operations. Commonly, 2D arrays are used to represents matrices. To create the matrix

$$
A = 
\begin{bmatrix} 
2.2 & 3.7 & 9.1\\ 
-4 & 3.1 & 1.3
\end{bmatrix} 
$$

we use:

In [78]:
A = np.array([[2.2, 3.7, 9.1], [-4.0, 3.1, 1.3]])
print(A)

[[ 2.2  3.7  9.1]
 [-4.   3.1  1.3]]


If we check the length of `A`:

In [79]:
print(len(A))

2


it reports the number of rows. To get the shape of the array, we use:

In [80]:
print(A.shape)

(2, 3)


which reports 2 rows and 3 columns (stored using a tuple). To get the number of rows and the number of columns,

In [81]:
num_rows = A.shape[0]
num_cols = A.shape[1]
print("Number of rows is {}, number of columns is {}.".format(num_rows, num_cols))

Number of rows is 2, number of columns is 3.


We can 'index' into a 2D array using two indices, the first for the row index and the second for the column index:

In [82]:
A02 = A[0, 2]
print(A02)

9.1


With `A[1]`, we will get the second row:

In [83]:
print(A[1])

[-4.   3.1  1.3]


We can iterate over the entries of `A` by iterating over the rows, and then the entry in each row:

In [84]:
for row in A:
    print("-----")
    for c in row:
        print(c)

-----
2.2
3.7
9.1
-----
-4.0
3.1
1.3


> **Warning:** NumPy has a `numpy.matrix` data structure. Its use is not recommended as it behaves inconsistently in some cases.

### 2D array (matrix) operations

For those who have seen matrices previously, the operations in this section will be familiar. For those who have not encountered matrices, you might want to revisit this section once matrices have been covered in the mathematics lectures.

#### Matrix-vector and matrix-matrix multiplication

We will consider the matrix $A$:

$$
A  = 
\begin{bmatrix}
3.4 & 2.6 \\
2.1 & 4.5
\end{bmatrix}
$$

and the vector $x$:

$$
x  = 
\begin{bmatrix}
0.2 \\ -1.1
\end{bmatrix}
$$

In [85]:
A = np.array([[3.4, 2.6], [2.1, 4.5]])
print("Matrix A:\n {}".format(A))

x = np.array([0.2, -1.1])
print("Vector x:\n {}".format(x))

Matrix A:
 [[3.4 2.6]
 [2.1 4.5]]
Vector x:
 [ 0.2 -1.1]


We can compute the matrix-vector product $y = Ax$ by:

In [86]:
y = A.dot(x)
print(y)

[-2.18 -4.53]


Matrix-matrix multiplication is performed similarly. Computing $C = AB$, where $A$, $B$, and $C$ are all matrices:

In [88]:
B = np.array([[1.3, 0], [0, 2.0]])

C = A.dot(B)
D=B.dot(A)
print(C)
print(D)

[[4.42 5.2 ]
 [2.73 9.  ]]
[[4.42 3.38]
 [4.2  9.  ]]


The inverse of a matrix ($A^{-1}$) and the determinant ($\det(A)$) can be computed using functions in the NumPy submodule `linalg`:

In [89]:
Ainv = np.linalg.inv(A)
print("Inverse of A:\n {}".format(Ainv))

Adet = np.linalg.det(A)
print("Determinant of A: {}".format(Adet))

Inverse of A:
 [[ 0.45731707 -0.26422764]
 [-0.21341463  0.34552846]]
Determinant of A: 9.839999999999998


> NumPy is large library, so it uses sub-modules to arrange functionality.

A very common matrix is the *identity matrix* $I$. We can create a $4 \times 4$ identity matrix using:

In [90]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array slicing

When working with arrays, it is often useful to extract subsets of an array. We might want just the first 3 entries of a long array, or we might want the second column of a 2D array (matrix). These operations are known as *array slicing* (https://en.wikipedia.org/wiki/Array_slicing).

We will explore slicing through examples. We start by creating an array filled with random values:

In [91]:
x = np.random.rand(5)
print(x)

[0.95664235 0.30659411 0.1437529  0.64935692 0.95945825]


Below are some slicing operations:

In [92]:
# Using ':' implies the whole range of indices, i.e. from 0 -> (length-1)
y = x[:]
print("Slice using '[:]' {}".format(y))

# Using '1:3' implies indices 1 -> 3 (not including 3)
y = x[1:3]
print("Slice using '[1:3]': {}".format(y))

# Using '2:-1' implies indices 2 -> second-from-last
y = x[2:-1]
print("Slice using '[2:-1]': {}".format(y))

# Using '2:-2' implies indices 2 -> third-from-last
y = x[2:-2]
print("Slice using '[2:-2]': {}".format(y))

Slice using '[:]' [0.95664235 0.30659411 0.1437529  0.64935692 0.95945825]
Slice using '[1:3]': [0.30659411 0.1437529 ]
Slice using '[2:-1]': [0.1437529  0.64935692]
Slice using '[2:-2]': [0.1437529]


> Note the use of the index `-1`. The index `-1` corresponds to the last entry in the array, and `-2` the 
> second last entry, etc. This is convenient if we know how far in from the end of an array a desired entry is.
> By using negative indices we can express this without reference to the length of the array.

If we want a slice to run from the start of an array, or to the end of an array, we do: 

In [93]:
# Using ':3' implies start -> 3 (not including 3)
y = x[:3]
print("Slice using '[:3]': {}".format(y))

# Using '4:' implies 4 -> end
y = x[4:]
print("Slice using '[4:]': {}".format(y))

# Using ':' implies start -> end
y = x[:]
print("Slice using '[:]': {}".format(y))

Slice using '[:3]': [0.95664235 0.30659411 0.1437529 ]
Slice using '[4:]': [0.95945825]
Slice using '[:]': [0.95664235 0.30659411 0.1437529  0.64935692 0.95945825]


Slicing can be applied to 2D arrays:

In [95]:
B = np.array([[1.3, 0], [0, 2.0]])
print(B)

# Extract second row
r = B[1, :]
print(r)

[[1.3 0. ]
 [0.  2. ]]
[0. 2.]


There is more to array slicing syntax, for example it is possible to extract every 3rd entry. If you need to extract a sub-array, check first if you can do it using the compact array slicing syntax.

# Exercises

Complete now the [07 Exercises](07%20Exercises.ipynb) notebook.